/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

const evenFib = () => {
  const biggest = 4000000;
  let arr = [];
  let sum = 0;

  let prior = 1;
  let current = 2;

  sum += current;

  while (current <= biggest) {
    let temp = prior + current;
    if (temp > biggest) break;
    prior = current;
    current = temp;
    if (current % 2 === 0) sum += current;
  }
  return sum;
};

console.log(evenFib());
